spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/cadastre
    username: sa
    password: sa

# https://medium.com/@harittweets/evolving-your-database-using-spring-boot-and-liquibase-844fcd7931da
# http://www.liquibase.org/documentation/changes/index.html
liquibase:
  change-log: classpath:db/liquibase-changelog.xml
